debug: false

data_storage:
  type: sqlite # sqlite or mysql
  mysql:
    host: '192.168.0.102'
    port: 3306
    database: 'testrw'
    username: 'root'
    password: 'Liao17303069590'
    params: '?autoReconnect=true&useSSL=false'
  hikari_settings:
    maximum_pool_size: 10
    minimum_idle: 10
    maximum_lifetime: 1800000
    keepalive_time: 0
    connection_timeout: 5000
状态信息:
  已领取: '&a已领取'
  可领取: '&a可领取'
  不可领取: '&c不可领取'

排行榜设置:
  充值排行榜: true
  金币排行榜: true
  在线排行榜: true
  排行榜更新频率: 1200 # 10分钟